module.exports = {
  Hindi: "hi",
  English: "en",
  Gujarati: "gu",
  Marathi: "mr",
  Tamil: "ta",
  Telugu: "te",
  Malayalam: "ml",
  Punjabi: "pa",
  Urdu: "ur",
  Kannada: "kn",
  Odia: "or",
  Assamese: "as",
  Bangla: "bn",
};
