module.exports = {
  Delhi: "Hindi",
  Maharashtra: "Marathi",
  "West Bengal": "Bangla",
  Karnataka: "Kannada",
  "Tamil Nadu": "Tamil",
  Telangana: "Telugu",
  Gujarat: "Gujarati",
  "Uttar Pradesh": "Hindi",
  Rajasthan: "Hindi",
  "Madhya Pradesh": "Hindi",
  "Andhra Pradesh": "Telugu",
  Bihar: "Hindi",
  Punjab: "Punjabi",
  Jharkhand: "Hindi",
  Haryana: "Hindi",
  "Jammu and Kashmir": "Hindi",
  Chhattisgarh: "Hindi",
  Chandigarh: "Punjabi",
  Assam: "Assamese",
  Odisha: "Odia",
  Kerala: "Malayalam",
  Uttarakhand: "Hindi",
  Tripura: "Bangla",
  Mizoram: "Hindi",
  Manipur: "Hindi",
  Puducherry: "Tamil",
  "Himachal Pradesh": "Hindi",
  Meghalaya: "Assamese",
  "Andaman and Nicobar Islands": "Hindi",
  Sikkim: "Assamese",
  Nagaland: "Assamese",
  "Arunachal Pradesh": "Assamese",
  Goa: "Hindi",
  "Dadra and Nagar Haveli": "Gujarati",
  "Daman and Diu": "Gujarati",
  Lakshadweep: "Malayalam",
};
